#.PHONY:all
#all:test kill
#test:test.c
#	gcc -o $@ $^
#mykill:mykill.c
#	gcc -o $@ $^
#clean:
#	rm -f test mykill


#myraise:myraise.c
#	gcc -o $@ $^
#.PHONY:clean
#clean:
#	rm -r myraises


# myabort:myabort.c
# 	gcc -o $@ $^
# .PHONY:clean
# clean:
# 	rm -r myabort

test:test.c
	gcc -o $@ $^
.PHONY:clean
clean:
	rm -r testS